name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-to-bucket:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
      - name: Install dependencies
        run: npm install
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Move .env file
        run: mv .env.prod .env
      - name: Build website
        run: npm run build
      - name: Copy to S3
        env:
          AWS_BUCKET: ${{ vars.AWS_BUCKET }}
        run: aws s3 sync ./build s3://$AWS_BUCKET
